#!/bin/sh

RCPORT=44000
BONNIP=192.168.1.3


[ "$1" != "" ] && RCPORT=$1

#export /opt/products/root/root_v5.26.00
export HOSTNAME=192.168.1.3
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/data/anemone/eudaq/bin

cd `dirname $0`

printf '\033[1;32;48m \t STARTING DAQ \033[0m \n'
printf '\033[22;33m\t Cleaning up first...  \033[0m \n'

#killall TestDataCollector.exe
#ssh eudet@$MVDIP "killall MVDProducer.exe" &
#killall TLUProducer.exe
#killall euLog
#killall euRun
printf '\033[22;31m\t End of killall \033[0m \n'

sleep 1

######################################################################
printf '\033[22;33m\t Making sure all data files are properly writeprotected \033[0m \n'
chmod a=rw data/run*.raw
printf '\033[22;32m\t ...Done!\033[0m \n'
cd bin
######################################################################
#printf '\033[22;33m\t Making sure TLU is accessible  \033[0m \n'
#./tlunoroot.exe
#sleep 1
######################################################################
#=====================================================================
printf '\033[22;33m\t Starting Subprocesses \033[0m \n'
#=====================================================================
######################################################################
# euRun
###############
printf '\033[22;33m\t RunControl \033[0m \n'
./euRun -x 0 -y 0 -w 450 -g 450 -a tcp://$RCPORT &
sleep 1
######################################################################
# euLog
###############
printf '\033[22;33m\t Logger  \033[0m \n'
./euLog -x 0 -y 450 -w 650 -g 550 -r tcp://$BONNIP:44000 &
sleep 1
######################################################################
# DataCollector
###############
printf '\033[22;33m\t TestDataCollector \033[0m \n'
xterm -sb -sl 1000 -geom 80x10-800-350 -fn fixed -T "Data Collector" -e './TestDataCollector.exe -r tcp://$BONNIP:$RCPORT' &
sleep 1
######################################################################
# NI Producer
###############
printf '\033[22;33m\t  NiProducer for linux  \033[0m \n'
xterm -sb -sl 1000 -geom 130x60-0-350 -T 'Ni Producer for Linux' -e './NiProducer.exe -r tcp://$BONNIP:$RCPORT' &
sleep 1
######################################################################
# TLU producer
###############
#printf '\033[22;33m\t  TLUProducer  \033[0m \n'
#xterm -sb -sl 1000 -geom 130x60-0-350 -T 'TLU Producer' -e './TLUProducer.exe -r tcp://$TLUIP:$RCPORT' &
#sleep 1
######################################################################
# Online Monitor
###############
printf '\033[22;33m\t  Online Monitor  \033[0m \n'
#./OnlineMon.exe -r tcp://$BONNIP:$RCPORT &
sleep 1
######################################################################

printf ' \n'
printf ' \n'
printf ' \n'
printf '\033[1;32;48m\t ...Done!\033[0m \n'
printf '\033[1;32;48mSTART OF DAQ COMPLETE\033[0m \n'
