//
// File generated by rootcint at Tue Jul 12 00:04:01 2011

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME tmpdIex2aDictOnlineMon
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ex2aDictOnlineMon.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void OnlineMonWindow_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void OnlineMonWindow_Dictionary();
   static void delete_OnlineMonWindow(void *p);
   static void deleteArray_OnlineMonWindow(void *p);
   static void destruct_OnlineMonWindow(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::OnlineMonWindow*)
   {
      ::OnlineMonWindow *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::OnlineMonWindow),0);
      static ::ROOT::TGenericClassInfo 
         instance("OnlineMonWindow", "./include/OnlineMonWindow.hh", 39,
                  typeid(::OnlineMonWindow), DefineBehavior(ptr, ptr),
                  0, &OnlineMonWindow_Dictionary, isa_proxy, 0,
                  sizeof(::OnlineMonWindow) );
      instance.SetDelete(&delete_OnlineMonWindow);
      instance.SetDeleteArray(&deleteArray_OnlineMonWindow);
      instance.SetDestructor(&destruct_OnlineMonWindow);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::OnlineMonWindow*)
   {
      return GenerateInitInstanceLocal((::OnlineMonWindow*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::OnlineMonWindow*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void OnlineMonWindow_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::OnlineMonWindow*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void CheckEOF_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void CheckEOF_Dictionary();
   static void *new_CheckEOF(void *p = 0);
   static void *newArray_CheckEOF(Long_t size, void *p);
   static void delete_CheckEOF(void *p);
   static void deleteArray_CheckEOF(void *p);
   static void destruct_CheckEOF(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CheckEOF*)
   {
      ::CheckEOF *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::CheckEOF),0);
      static ::ROOT::TGenericClassInfo 
         instance("CheckEOF", "./include/CheckEOF.hh", 16,
                  typeid(::CheckEOF), DefineBehavior(ptr, ptr),
                  0, &CheckEOF_Dictionary, isa_proxy, 0,
                  sizeof(::CheckEOF) );
      instance.SetNew(&new_CheckEOF);
      instance.SetNewArray(&newArray_CheckEOF);
      instance.SetDelete(&delete_CheckEOF);
      instance.SetDeleteArray(&deleteArray_CheckEOF);
      instance.SetDestructor(&destruct_CheckEOF);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CheckEOF*)
   {
      return GenerateInitInstanceLocal((::CheckEOF*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CheckEOF*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void CheckEOF_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::CheckEOF*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrapper around operator delete
   static void delete_OnlineMonWindow(void *p) {
      delete ((::OnlineMonWindow*)p);
   }
   static void deleteArray_OnlineMonWindow(void *p) {
      delete [] ((::OnlineMonWindow*)p);
   }
   static void destruct_OnlineMonWindow(void *p) {
      typedef ::OnlineMonWindow current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::OnlineMonWindow

namespace ROOT {
   // Wrappers around operator new
   static void *new_CheckEOF(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::CheckEOF : new ::CheckEOF;
   }
   static void *newArray_CheckEOF(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::CheckEOF[nElements] : new ::CheckEOF[nElements];
   }
   // Wrapper around operator delete
   static void delete_CheckEOF(void *p) {
      delete ((::CheckEOF*)p);
   }
   static void deleteArray_CheckEOF(void *p) {
      delete [] ((::CheckEOF*)p);
   }
   static void destruct_CheckEOF(void *p) {
      typedef ::CheckEOF current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::CheckEOF

/********************************************************
* tmp/ex2aDictOnlineMon.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableex2aDictOnlineMon();

extern "C" void G__set_cpp_environmentex2aDictOnlineMon() {
  G__cpp_reset_tagtableex2aDictOnlineMon();
}
#include <new>
extern "C" int G__cpp_dllrevex2aDictOnlineMon() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* OnlineMonWindow */
static int G__ex2aDictOnlineMon_413_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const OnlineMonWindow*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((OnlineMonWindow*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((OnlineMonWindow*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((OnlineMonWindow*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((OnlineMonWindow*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((OnlineMonWindow*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   G__va_arg_buf G__va_arg_bufobj;
   G__va_arg_put(&G__va_arg_bufobj, libp, 2);
      ((OnlineMonWindow*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), G__va_arg_bufobj);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   OnlineMonWindow* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new OnlineMonWindow(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) OnlineMonWindow(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->registerTreeItem(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->makeTreeItemSummary(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->addTreeItemSummary(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      ((OnlineMonWindow*) G__getstructoffset())->registerHisto(*((string*) G__int(libp->para[0])), (TH1*) G__int(libp->para[1])
, *((string*) G__int(libp->para[2])), (const unsigned int) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ((OnlineMonWindow*) G__getstructoffset())->registerHisto(*((string*) G__int(libp->para[0])), (TH1*) G__int(libp->para[1])
, *((string*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      ((OnlineMonWindow*) G__getstructoffset())->registerHisto(*((string*) G__int(libp->para[0])), (TH1*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->actor((TGListTreeItem*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->actorMenu((TGListTreeItem*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->registerPlane((char*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->autoUpdate();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->setCollections(*((vector<BaseCollection*>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Write();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->AutoReset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->ChangeReduce((Long_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->Quit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->SnapShot();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->setRootFileName(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->UpdateRunNumber((const int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->UpdateEventNumber((const int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->UpdateStatus(*((const string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->UpdateTotalEventNumber((const int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->setEventNumber((const int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->setRunNumber((const int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->setAutoReset((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const OnlineMonWindow*) G__getstructoffset())->getAutoReset());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->setReduce((const unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((OnlineMonWindow*) G__getstructoffset())->getReduce());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->setUpdate((const unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->increaseAnalysedEventsCounter();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->ExecuteEvent((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (TObject*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_413_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineMonWindow*) G__getstructoffset())->SetOnlineMon((RootMonitor*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef OnlineMonWindow G__TOnlineMonWindow;
static int G__ex2aDictOnlineMon_413_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (OnlineMonWindow*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((OnlineMonWindow*) (soff+(sizeof(OnlineMonWindow)*i)))->~G__TOnlineMonWindow();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (OnlineMonWindow*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((OnlineMonWindow*) (soff))->~G__TOnlineMonWindow();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* CheckEOF */
static int G__ex2aDictOnlineMon_468_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CheckEOF* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CheckEOF[n];
     } else {
       p = new((void*) gvp) CheckEOF[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CheckEOF;
     } else {
       p = new((void*) gvp) CheckEOF;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_CheckEOF));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_468_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CheckEOF*) G__getstructoffset())->TimerLoop();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_468_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CheckEOF*) G__getstructoffset())->EventReceived();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_468_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CheckEOF*) G__getstructoffset())->setCollections(*((vector<BaseCollection*>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_468_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((CheckEOF*) G__getstructoffset())->startChecking((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((CheckEOF*) G__getstructoffset())->startChecking();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ex2aDictOnlineMon_468_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CheckEOF*) G__getstructoffset())->setRootFileName(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ex2aDictOnlineMon_468_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   CheckEOF* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new CheckEOF(*(CheckEOF*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_CheckEOF));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CheckEOF G__TCheckEOF;
static int G__ex2aDictOnlineMon_468_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CheckEOF*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CheckEOF*) (soff+(sizeof(CheckEOF)*i)))->~G__TCheckEOF();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CheckEOF*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CheckEOF*) (soff))->~G__TCheckEOF();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__ex2aDictOnlineMon_468_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CheckEOF* dest = (CheckEOF*) G__getstructoffset();
   *dest = *(CheckEOF*) libp->para[0].ref;
   const CheckEOF& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* OnlineMonWindow */

/* CheckEOF */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncex2aDictOnlineMon {
 public:
  G__Sizep2memfuncex2aDictOnlineMon(): p(&G__Sizep2memfuncex2aDictOnlineMon::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncex2aDictOnlineMon::*p)();
};

size_t G__get_sizep2memfuncex2aDictOnlineMon()
{
  G__Sizep2memfuncex2aDictOnlineMon a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceex2aDictOnlineMon() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow))) {
     OnlineMonWindow *G__Lderived;
     G__Lderived=(OnlineMonWindow*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow),G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow),G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow),G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow),G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow),G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow),G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow),G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableex2aDictOnlineMon() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 4 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SimpleStandardHit>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardHitcOallocatorlESimpleStandardHitgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardHitcOallocatorlESimpleStandardHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardHitcOallocatorlESimpleStandardHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardHitcOallocatorlESimpleStandardHitgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardHitcOallocatorlESimpleStandardHitgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SimpleStandardCluster>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardClustercOallocatorlESimpleStandardClustergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardClustercOallocatorlESimpleStandardClustergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardClustercOallocatorlESimpleStandardClustergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardClustercOallocatorlESimpleStandardClustergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardClustercOallocatorlESimpleStandardClustergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SimpleStandardPlane>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardPlanecOallocatorlESimpleStandardPlanegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardPlanecOallocatorlESimpleStandardPlanegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardPlanecOallocatorlESimpleStandardPlanegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardPlanecOallocatorlESimpleStandardPlanegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardPlanecOallocatorlESimpleStandardPlanegRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SimpleStandardPlane,HitmapHistos*>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplESimpleStandardPlanecOHitmapHistosmUcOlesslESimpleStandardPlanegRcOallocatorlEpairlEconstsPSimpleStandardPlanecOHitmapHistosmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SimpleStandardPlane,HitmapHistos*,less<SimpleStandardPlane> >",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplESimpleStandardPlanecOHitmapHistosmUcOlesslESimpleStandardPlanegRcOallocatorlEpairlEconstsPSimpleStandardPlanecOHitmapHistosmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SimpleStandardPlaneDouble,CorrelationHistos*>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplESimpleStandardPlaneDoublecOCorrelationHistosmUcOlesslESimpleStandardPlaneDoublegRcOallocatorlEpairlEconstsPSimpleStandardPlaneDoublecOCorrelationHistosmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<SimpleStandardPlaneDouble,CorrelationHistos*,less<SimpleStandardPlaneDouble> >",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplESimpleStandardPlaneDoublecOCorrelationHistosmUcOlesslESimpleStandardPlaneDoublegRcOallocatorlEpairlEconstsPSimpleStandardPlaneDoublecOCorrelationHistosmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BaseCollection*>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TGListTreeItem*>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOTGListTreeItemmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTGListTreeItemmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TGListTreeItem*>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOTGListTreeItemmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTGListTreeItemmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TGListTreeItem*,less<string> >",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOTGListTreeItemmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTGListTreeItemmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TGListTreeItem*,std::string>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplETGListTreeItemmUcOstringcOlesslETGListTreeItemmUgRcOallocatorlEpairlETGListTreeItemmUsPconstcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TGListTreeItem*,string>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplETGListTreeItemmUcOstringcOlesslETGListTreeItemmUgRcOallocatorlEpairlETGListTreeItemmUsPconstcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TGListTreeItem*,string,less<TGListTreeItem*> >",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplETGListTreeItemmUcOstringcOlesslETGListTreeItemmUgRcOallocatorlEpairlETGListTreeItemmUsPconstcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TH1*>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH1*>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TH1*,less<string> >",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::vector<std::string> >",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<string,allocator<string> > >",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<string,allocator<string> >,less<string> >",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,unsigned int>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOunsignedsPintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,unsigned int>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOunsignedsPintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,unsigned int,less<string> >",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOunsignedsPintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGListTreeItem*>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* OnlineMonWindow */
static void G__setup_memvarOnlineMonWindow(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow));
   { OnlineMonWindow *p; p=(OnlineMonWindow*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_string),-1,-1,2,"_rootfilename=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgR),G__defined_typename("vector<BaseCollection*>"),-1,2,"_colls=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TTimer),-1,-1,2,"timer=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGHorizontalFrame),-1,-1,2,"Hfrm_windows=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGVerticalFrame),-1,-1,2,"Hfrm_left=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGVerticalFrame),-1,-1,2,"Hfrm_right=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGCanvas),-1,-1,2,"Cvs_left=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TRootEmbeddedCanvas),-1,-1,2,"ECvs_right=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGListTree),-1,-1,2,"LTr_left=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,2,"_activeHistos=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGToolBar),-1,-1,2,"tb=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGButton),-1,-1,2,"button_save=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGButton),-1,-1,2,"button_reset=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGButton),-1,-1,2,"button_autoreset=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGButton),-1,-1,2,"button_quit=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGButton),-1,-1,2,"button_snapshot=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGStatusBar),-1,-1,2,"fStatusBar=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOTGListTreeItemmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTGListTreeItemmUgRsPgRsPgR),G__defined_typename("map<std::string,TGListTreeItem*>"),-1,2,"_treeMap=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplETGListTreeItemmUcOstringcOlesslETGListTreeItemmUgRcOallocatorlEpairlETGListTreeItemmUsPconstcOstringgRsPgRsPgR),G__defined_typename("map<TGListTreeItem*,std::string>"),-1,2,"_treeBackMap=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR),G__defined_typename("map<std::string,TH1*>"),-1,2,"_hitmapMap=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),G__defined_typename("map<std::string,std::vector<std::string> >"),-1,2,"_summaryMap=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),G__defined_typename("map<std::string,std::string>"),-1,2,"_hitmapOptions=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_maplEstringcOunsignedsPintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPintgRsPgRsPgR),G__defined_typename("map<std::string,unsigned int>"),-1,2,"_logScaleMap=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGListTreeItem),-1,-1,2,"Itm_Eudet=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGListTreeItem),-1,-1,2,"Itm_DUT=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGListTreeItem),-1,-1,2,"Itm_EudetHM=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGListTreeItem),-1,-1,2,"Itm_DUTHM=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TGNumberEntry),-1,-1,2,"nen_reduce=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR),G__defined_typename("vector<TGListTreeItem*>"),-1,2,"Itm_EudetHM_Vec=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TH2F),-1,-1,2,"h1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TH2F),-1,-1,2,"h2=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,2,"_eventnum=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,2,"_runnum=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"_autoreset=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,2,"_reduce=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,2,"_reduceUpdate=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,2,"_analysedEvents=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TContextMenu),-1,-1,2,"CtxMenu=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_RootMonitor),-1,-1,2,"rmon=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"snapshot_sequence=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* CheckEOF */
static void G__setup_memvarCheckEOF(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_CheckEOF));
   { CheckEOF *p; p=(CheckEOF*)0x1000; if (p) { }
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"_isEOF=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TTimer),-1,-1,2,"timer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_vectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgR),G__defined_typename("vector<BaseCollection*>"),-1,2,"_colls=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_string),-1,-1,2,"_rootfilename=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarex2aDictOnlineMon() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncOnlineMonWindow(void) {
   /* OnlineMonWindow */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow));
   G__memfunc_setup("GetListOfSignals",1602,G__ex2aDictOnlineMon_413_0_1, 85, G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__ex2aDictOnlineMon_413_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__ex2aDictOnlineMon_413_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LowPriority",1172,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("EmitVA",550,G__ex2aDictOnlineMon_413_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__ex2aDictOnlineMon_413_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ChangedBy",869,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Message",709,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("OnlineMonWindow",1543,G__ex2aDictOnlineMon_413_0_26, 105, G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_OnlineMonWindow), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("registerTreeItem",1668,G__ex2aDictOnlineMon_413_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("makeTreeItemSummary",1963,G__ex2aDictOnlineMon_413_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addTreeItemSummary",1846,G__ex2aDictOnlineMon_413_0_29, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 - item u 'string' - 0 - histoitem", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("registerHisto",1388,G__ex2aDictOnlineMon_413_0_30, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'string' - 0 - tree U 'TH1' - 0 - h "
"u 'string' - 0 '\"\"' op h - - 10 'kLin' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("actor",537,G__ex2aDictOnlineMon_413_0_31, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGListTreeItem' - 0 - item i - 'Int_t' 0 - btn", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("actorMenu",942,G__ex2aDictOnlineMon_413_0_32, 121, -1, -1, 0, 4, 1, 1, 0, 
"U 'TGListTreeItem' - 0 - item i - 'Int_t' 0 - btn "
"i - 'Int_t' 0 - x i - 'Int_t' 0 - y", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("registerPlane",1365,G__ex2aDictOnlineMon_413_0_33, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 0 - sensor i - - 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("autoUpdate",1052,G__ex2aDictOnlineMon_413_0_34, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setCollections",1483,G__ex2aDictOnlineMon_413_0_35, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<BaseCollection*,allocator<BaseCollection*> >' 'vector<BaseCollection*>' 0 - colls", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Write",523,G__ex2aDictOnlineMon_413_0_36, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,G__ex2aDictOnlineMon_413_0_37, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AutoReset",924,G__ex2aDictOnlineMon_413_0_38, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangeReduce",1182,G__ex2aDictOnlineMon_413_0_39, 121, -1, -1, 0, 1, 1, 1, 0, "l - 'Long_t' 0 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Quit",419,G__ex2aDictOnlineMon_413_0_40, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SnapShot",816,G__ex2aDictOnlineMon_413_0_41, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setRootFileName",1521,G__ex2aDictOnlineMon_413_0_42, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - rootfilename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateRunNumber",1537,G__ex2aDictOnlineMon_413_0_43, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 10 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateEventNumber",1742,G__ex2aDictOnlineMon_413_0_44, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 10 - event", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateStatus",1255,G__ex2aDictOnlineMon_413_0_45, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 10 - status", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateTotalEventNumber",2258,G__ex2aDictOnlineMon_413_0_46, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 10 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setEventNumber",1463,G__ex2aDictOnlineMon_413_0_47, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 10 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setRunNumber",1258,G__ex2aDictOnlineMon_413_0_48, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 10 - num", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setAutoReset",1256,G__ex2aDictOnlineMon_413_0_49, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - reset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getAutoReset",1244,G__ex2aDictOnlineMon_413_0_50, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setReduce",932,G__ex2aDictOnlineMon_413_0_51, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 10 - red", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getReduce",920,G__ex2aDictOnlineMon_413_0_52, 104, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setUpdate",943,G__ex2aDictOnlineMon_413_0_53, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 10 - up", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("increaseAnalysedEventsCounter",3024,G__ex2aDictOnlineMon_413_0_54, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ExecuteEvent",1237,G__ex2aDictOnlineMon_413_0_55, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - event i - 'Int_t' 0 - px "
"i - 'Int_t' 0 - py U 'TObject' - 0 - sel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetOnlineMon",1211,G__ex2aDictOnlineMon_413_0_56, 121, -1, -1, 0, 1, 1, 1, 0, "U 'RootMonitor' - 0 - mymon", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~OnlineMonWindow", 1669, G__ex2aDictOnlineMon_413_0_57, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncCheckEOF(void) {
   /* CheckEOF */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_CheckEOF));
   G__memfunc_setup("CheckEOF",696,G__ex2aDictOnlineMon_468_0_1, 105, G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_CheckEOF), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TimerLoop",923,G__ex2aDictOnlineMon_468_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EventReceived",1321,G__ex2aDictOnlineMon_468_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setCollections",1483,G__ex2aDictOnlineMon_468_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<BaseCollection*,allocator<BaseCollection*> >' 'vector<BaseCollection*>' 0 - colls", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("startChecking",1354,G__ex2aDictOnlineMon_468_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 '10000' mtime", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setRootFileName",1521,G__ex2aDictOnlineMon_468_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - name", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("CheckEOF", 696, G__ex2aDictOnlineMon_468_0_7, (int) ('i'), G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_CheckEOF), -1, 0, 1, 1, 1, 0, "u 'CheckEOF' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~CheckEOF", 822, G__ex2aDictOnlineMon_468_0_8, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__ex2aDictOnlineMon_468_0_9, (int) ('u'), G__get_linked_tagnum(&G__ex2aDictOnlineMonLN_CheckEOF), -1, 1, 1, 1, 1, 0, "u 'CheckEOF' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncex2aDictOnlineMon() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalex2aDictOnlineMon() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcex2aDictOnlineMon() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ex2aDictOnlineMonLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGVerticalFrame = { "TGVerticalFrame" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGHorizontalFrame = { "TGHorizontalFrame" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGCanvas = { "TGCanvas" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGListTreeItem = { "TGListTreeItem" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGListTree = { "TGListTree" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TContextMenu = { "TContextMenu" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGButton = { "TGButton" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGToolBar = { "TGToolBar" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGStatusBar = { "TGStatusBar" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_vectorlESimpleStandardHitcOallocatorlESimpleStandardHitgRsPgR = { "vector<SimpleStandardHit,allocator<SimpleStandardHit> >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardHitcOallocatorlESimpleStandardHitgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SimpleStandardHit,allocator<SimpleStandardHit> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_vectorlESimpleStandardClustercOallocatorlESimpleStandardClustergRsPgR = { "vector<SimpleStandardCluster,allocator<SimpleStandardCluster> >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardClustercOallocatorlESimpleStandardClustergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SimpleStandardCluster,allocator<SimpleStandardCluster> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_vectorlESimpleStandardPlanecOallocatorlESimpleStandardPlanegRsPgR = { "vector<SimpleStandardPlane,allocator<SimpleStandardPlane> >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardPlanecOallocatorlESimpleStandardPlanegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SimpleStandardPlane,allocator<SimpleStandardPlane> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_RootMonitor = { "RootMonitor" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_maplESimpleStandardPlanecOHitmapHistosmUcOlesslESimpleStandardPlanegRcOallocatorlEpairlEconstsPSimpleStandardPlanecOHitmapHistosmUgRsPgRsPgR = { "map<SimpleStandardPlane,HitmapHistos*,less<SimpleStandardPlane>,allocator<pair<const SimpleStandardPlane,HitmapHistos*> > >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_maplESimpleStandardPlaneDoublecOCorrelationHistosmUcOlesslESimpleStandardPlaneDoublegRcOallocatorlEpairlEconstsPSimpleStandardPlaneDoublecOCorrelationHistosmUgRsPgRsPgR = { "map<SimpleStandardPlaneDouble,CorrelationHistos*,less<SimpleStandardPlaneDouble>,allocator<pair<const SimpleStandardPlaneDouble,CorrelationHistos*> > >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_OnlineMonWindow = { "OnlineMonWindow" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_vectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgR = { "vector<BaseCollection*,allocator<BaseCollection*> >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BaseCollection*,allocator<BaseCollection*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_maplEstringcOTGListTreeItemmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTGListTreeItemmUgRsPgRsPgR = { "map<string,TGListTreeItem*,less<string>,allocator<pair<const string,TGListTreeItem*> > >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_maplETGListTreeItemmUcOstringcOlesslETGListTreeItemmUgRcOallocatorlEpairlETGListTreeItemmUsPconstcOstringgRsPgRsPgR = { "map<TGListTreeItem*,string,less<TGListTreeItem*>,allocator<pair<TGListTreeItem* const,string> > >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR = { "map<string,TH1*,less<string>,allocator<pair<const string,TH1*> > >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR = { "map<string,vector<string,allocator<string> >,less<string>,allocator<pair<const string,vector<string,allocator<string> > > > >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_maplEstringcOunsignedsPintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPintgRsPgRsPgR = { "map<string,unsigned int,less<string>,allocator<pair<const string,unsigned int> > >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_vectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR = { "vector<TGListTreeItem*,allocator<TGListTreeItem*> >" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGListTreeItem*,allocator<TGListTreeItem*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ex2aDictOnlineMonLN_CheckEOF = { "CheckEOF" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableex2aDictOnlineMon() {
  G__ex2aDictOnlineMonLN_TObject.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_string.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TList.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TTimer.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TQObject.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TQObjSender.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGObject.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGWindow.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGFrame.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGCompositeFrame.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGVerticalFrame.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGHorizontalFrame.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGMainFrame.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGCanvas.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGListTreeItem.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGListTree.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TH1.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TH2F.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TContextMenu.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGButton.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGToolBar.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGStatusBar.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_TGNumberEntry.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_vectorlESimpleStandardHitcOallocatorlESimpleStandardHitgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardHitcOallocatorlESimpleStandardHitgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_vectorlESimpleStandardClustercOallocatorlESimpleStandardClustergRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardClustercOallocatorlESimpleStandardClustergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_vectorlESimpleStandardPlanecOallocatorlESimpleStandardPlanegRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardPlanecOallocatorlESimpleStandardPlanegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_RootMonitor.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_maplESimpleStandardPlanecOHitmapHistosmUcOlesslESimpleStandardPlanegRcOallocatorlEpairlEconstsPSimpleStandardPlanecOHitmapHistosmUgRsPgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_maplESimpleStandardPlaneDoublecOCorrelationHistosmUcOlesslESimpleStandardPlaneDoublegRcOallocatorlEpairlEconstsPSimpleStandardPlaneDoublecOCorrelationHistosmUgRsPgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_OnlineMonWindow.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_vectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_maplEstringcOTGListTreeItemmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTGListTreeItemmUgRsPgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_maplETGListTreeItemmUcOstringcOlesslETGListTreeItemmUgRcOallocatorlEpairlETGListTreeItemmUsPconstcOstringgRsPgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_maplEstringcOunsignedsPintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPintgRsPgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_vectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ex2aDictOnlineMonLN_CheckEOF.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableex2aDictOnlineMon() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TObject);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_string);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TList);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TTimer);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TQObject);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TQObjSender);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGObject);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGVerticalFrame);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGHorizontalFrame);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGCanvas);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGListTreeItem);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGListTree);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TH1);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TH2F);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TContextMenu);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGButton);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGToolBar);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGStatusBar);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardHitcOallocatorlESimpleStandardHitgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardHitcOallocatorlESimpleStandardHitgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardClustercOallocatorlESimpleStandardClustergRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardClustercOallocatorlESimpleStandardClustergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_vectorlESimpleStandardPlanecOallocatorlESimpleStandardPlanegRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlESimpleStandardPlanecOallocatorlESimpleStandardPlanegRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_RootMonitor);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_maplESimpleStandardPlanecOHitmapHistosmUcOlesslESimpleStandardPlanegRcOallocatorlEpairlEconstsPSimpleStandardPlanecOHitmapHistosmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_maplESimpleStandardPlaneDoublecOCorrelationHistosmUcOlesslESimpleStandardPlaneDoublegRcOallocatorlEpairlEconstsPSimpleStandardPlaneDoublecOCorrelationHistosmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_OnlineMonWindow),sizeof(OnlineMonWindow),-1,62464,(char*)NULL,G__setup_memvarOnlineMonWindow,G__setup_memfuncOnlineMonWindow);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_vectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlEBaseCollectionmUcOallocatorlEBaseCollectionmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_maplEstringcOTGListTreeItemmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTGListTreeItemmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_maplETGListTreeItemmUcOstringcOlesslETGListTreeItemmUgRcOallocatorlEpairlETGListTreeItemmUsPconstcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_maplEstringcOTH1mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTH1mUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_maplEstringcOunsignedsPintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_vectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_reverse_iteratorlEvectorlETGListTreeItemmUcOallocatorlETGListTreeItemmUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ex2aDictOnlineMonLN_CheckEOF),sizeof(CheckEOF),-1,256,(char*)NULL,G__setup_memvarCheckEOF,G__setup_memfuncCheckEOF);
}
extern "C" void G__cpp_setupex2aDictOnlineMon(void) {
  G__check_setup_version(30051515,"G__cpp_setupex2aDictOnlineMon()");
  G__set_cpp_environmentex2aDictOnlineMon();
  G__cpp_setup_tagtableex2aDictOnlineMon();

  G__cpp_setup_inheritanceex2aDictOnlineMon();

  G__cpp_setup_typetableex2aDictOnlineMon();

  G__cpp_setup_memvarex2aDictOnlineMon();

  G__cpp_setup_memfuncex2aDictOnlineMon();
  G__cpp_setup_globalex2aDictOnlineMon();
  G__cpp_setup_funcex2aDictOnlineMon();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncex2aDictOnlineMon();
  return;
}
class G__cpp_setup_initex2aDictOnlineMon {
  public:
    G__cpp_setup_initex2aDictOnlineMon() { G__add_setup_func("ex2aDictOnlineMon",(G__incsetup)(&G__cpp_setupex2aDictOnlineMon)); G__call_setup_funcs(); }
   ~G__cpp_setup_initex2aDictOnlineMon() { G__remove_setup_func("ex2aDictOnlineMon"); }
};
G__cpp_setup_initex2aDictOnlineMon G__cpp_setup_initializerex2aDictOnlineMon;

